version: '3'

services:

    webapp:
        build: ./build/
        image: web-php7.3
        container_name: web-app
        volumes:
            - "./app:/app"
        restart: always
        ports:
            - 80:80

    mysql:
        image: mysql:5.6
        container_name: web-mysql
        volumes:
            - "./db:/var/lib/mysql"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "Azerty;11"